### ISSUE TITLE
Issue with nested attributes

### ISSUE THREAD

**Issue by Slackercode** [mrcrowl/vscode-easy-less#27]
The compiler creates a whitespace between the selector and the nested attricture, for example:
```less
@base: rgba(31,187,166,1);
button{
background:@base;
    [raised]
    {
    box-shadow: inset 0px -2px 0 1px darken(@base,5%);
    }
}
```

compiles to:

```css
button{
background:#1fbba6;
}
button [raised]
{
    box-shadow: inset 0px -2px 0 1px #1ba593
}
```

Which doesn't work obviously, it should output `button[raised]`;
