### ISSUE TITLE
how can i activate auto prefix for output file

### ISSUE THREAD

**Issue by NikosEfthias** [mrcrowl/vscode-easy-less#4]
how can i activate auto prefix for output file

**Comment by RadhiFadlillah** [comment]
@NikosEfthias have you found out how to do it ?

**Comment by NikosEfthias** [comment]
@RadhiFadlillah nope i didnt i just closed the issue due to the age . no response from the writers

**Comment by mrcrowl** [comment]
@NikosEfthias sorry I ignored this because it was closed. Can you please
elaborate on what the request is? What do you mean by auto prefix? Could
you provide an example?
On Sun, 20 Nov 2016 at 12:39 PM, Nikos Efthias <notifications@github.com>
wrote:

@RadhiFadlillah <https://github.com/RadhiFadlillah> nope i didnt i just
closed the issue due to the age . no response from the writers

—
You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub
<https://github.com/mrcrowl/vscode-easy-less/issues/4#issuecomment-261747430>,
or mute the thread

**Comment by NikosEfthias** [comment]
using autoprefixing such as --webkit-- --moz--

**Comment by RadhiFadlillah** [comment]
For example, in [brackets-less-autocompile](https://github.com/jdiehl/brackets-less-autocompile) we can create configuration file like this :

```
{
    "compress": true,
    "strictMath": true,
    "autoprefixer": "last 2 versions; > 5%"
}
```

Using this configuration, when I save a `LESS` file like this :

```less
* {
    box-sizing: border-box;
    font-family: 'Source Sans Pro', 'sans-serif';
    user-select: none;
}
```

It will compile into `CSS` file like this :

```css
* {
    box-sizing: border-box;
    font-family: 'Source Sans Pro', 'sans-serif';
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
}
```
