### ISSUE TITLE
Problems with calc: support for strictMath or the new math options

### ISSUE THREAD

**Issue by LenAnderson** [mrcrowl/vscode-easy-less#44]
As described here:  
http://lesscss.org/usage/#less-options-math

Currently the compiler calculates anything that remotely looks like a calculation and just ignores units. As a result `100vw - 100px` becomes `0vw`. For a long time LESS has offered the `strictMath` option to avoid this and only apply calculation in superfluous parentheses.  
Recently this option has been deprecated in favor of a more flexible `math` option that offers the two previously available modes along with a couple of others.

While the aggressive calculation can be avoided by typing `~"100vw - 100px"` support for either the new "math" option or just the old "strictMath" option would make life a lot easier and the LESS code more readable. It would also address the issue raised in #35.

**Comment by LoganGerber** [comment]
This should be changed from Enhancement to Bug. With the settings the way they currently are, something like this is rendered impossible:

```less
@size1 = 30px;
@size2 = 40px;

.div {
    height: calc(100% - @size1 - @size2);
}
```

The above should be compiled to the following css:

```css
.div {
    height: calc(100% - 30px - 40px);
}
```

With the settings the way they are, this is the css output:

```css
.div {
    height: calc(30%);
}
```

And with the suggested bandaid fix in the OP, this is the css output:

```css
.div {
    height: calc(100% - @size1 - @size2); // INVALID CSS
}
```

**Comment by LenAnderson** [comment]
@LoganGerber more crutches, but you can work around your problem by typing this:

```less
.div {
	height: ~"calc(100%" - @size1 - @size2 ~")";
}
```

which will turn into:

```css
.div {
  height: calc(100% - -10px );
}
```
