### ISSUE TITLE
Variable multiple does not work

### ISSUE THREAD

**Issue by airsence** [mrcrowl/vscode-easy-less#62]
Version 1.6.3

When I use auto compile from Less to CSS, I found that the multiple calculation is not working.

In Less:

```Less
@col = 8.33%;
:root{
--header-logo-height: 10 * @col;
}
```

In CSS:

```CSS
:root{
--header-logo-height: 10 * 8.33%;
}
```
